import asyncio
import sys
import os

sys.path.insert(0, os.getcwd())

from src.agentic.core.orchestrator_v3 import OrchestratorV3
from src.agentic.core.plugins.simple_planner import SimplePlanner
from src.agentic.core.plugins.aider_executor import AiderExecutor
from src.agentic.core.plugins.sentinel import SentinelVerifier
from src.agentic.core.plugins.artifact_generator import ArtifactGenerator
from src.agentic.core.plugins.task_board_manager import TaskBoardManager

async def run_governance_fix():
    print("🚀 STARTING SELF-REPAIR TASK: Governance System Integration")
    
    orchestrator = OrchestratorV3(
        planner=SimplePlanner(),
        executor=AiderExecutor(),
        verifier=SentinelVerifier(),
        artifact_gen=ArtifactGenerator(),
        task_board=TaskBoardManager()
    )
    
    task_description = """
    CRITICAL UPDATE for 'src/agentic/core/plugins/simple_planner.py'.
    
    We need to inject the SYSTEM CONSTITUTION into the planning phase.
    The planner is currently unaware of project rules.
    
    INSTRUCTIONS:
    1. Edit 'src/agentic/core/plugins/simple_planner.py'.
    2. Add a helper method '_read_constitution(self) -> str' that:
       - Tries to read '00_GENESIS/YBIS_CONSTITUTION.md' from the project root.
       - Returns the content if found.
       - Returns a default string "Follow standard software engineering best practices." if not found.
    3. Update the '_build_prompt' method to:
       - Call '_read_constitution()'.
       - Include the constitution text in the prompt under a new section "### SYSTEM CONSTITUTION (MUST FOLLOW):".
       - Ensure the prompt instructs the LLM to strictly adhere to these rules when planning.
       
    OBJECTIVE: 
    Ensure every plan generated by the system complies with the YBIS Constitution.
    """
    
    task_id = "SELF-REPAIR-002"
    
    print(f"▶️ Delegating Task {task_id} to Orchestrator...")
    await orchestrator.run_task(task_id, task_description)
    print("✅ Orchestrator finished execution.")

if __name__ == "__main__":
    asyncio.run(run_governance_fix())
